language: python
matrix:
  include:
    - python: "3.7"
      dist: xenial

install:
  - pip install -r requirements.txt
script:
  - python mechanize/blind_sqlinjection.py
  - python mechanize/bruteforce_wordlist.py
  - python mechanize/cj_detector.py
  - python mechanize/command_execution.py
  - python mechanize/hsts_detector.py
